world/wall/urls.py
from django.conf.urls import *
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views

app_name = 'wall'

urlpatterns = [
    url(r'^$', views.index.as_view(), name='home'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^users/(?P<pk>[0-9]+)/$', views.Profile, name='profile'),
    url(r'signup/', views.SignUp, name='signup'),
    url(r'^publish/$', views.publish, name='publish'),
]

world/world/urls.py
from django.conf.urls import *
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wall/', include('wall.urls')),
]

world/wall/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Message(models.Model):
    """The Messgae published on the Wall
     I am using another Django default User Along with its authorization & authenticate Methods """

    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    messages_text = models.CharField(max_length=250)
    messages_date = models.DateTimeField('date published')
    def __str__ (self):
        return self.messages_text

world/wall/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

    def clean_email(self):
        # Race Condition here !
        # Better method is to use Abstract class for Users (where we can have unique email constrain).
        # It took alot of time and had few issues. So a hotfix is made here
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

world/wall/views.py
    # Create your views here.
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404,render_to_response
from django.urls import reverse,reverse_lazy
from django.views import generic
from django.core.mail import send_mail
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from wall.forms import SignUpForm
from .models import *

def SignUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        #Validating & Extracting Inputs from form
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            email = form.cleaned_data.get('email')

            user = authenticate(username=username, password=raw_password, email=email)

            #Sending Email
            send_mail(
                'Wellcome '+username+" !",
                'Thanks For Joinng the Wall .',
                'noreply@WorldWall.com',
                [email],
                fail_silently=False,
            )

            #Login Now
            return HttpResponseRedirect(reverse_lazy('wall:login',))
    else:
        # try again with the form if inputs aren't valid
        form = SignUpForm()
    return render(request, 'wall/signup.html', {'form': form})

class index(generic.ListView):
    template_name = 'wall/index.html'
    context_object_name = 'comments'

    def get_queryset(self):
        """Return ALL published questions Ordered by the date ."""
        return Message.objects.order_by('-messages_date')

def Profile(request,pk):
        """User profiles with their publications and info like email & name"""
        userid=get_object_or_404(User, pk=pk)
        return render(request,'wall/profile.html',
            context={
            'user':userid,
            'comments': list(Message.objects.filter(user_id=pk).order_by('-messages_date'))
            })

@login_required
def publish(request):
        """Method to puclish on wall what user wants to say """
        if(request.POST['message_txt']!=""):
                new_message = Message(user_id =request.user, messages_text=request.POST['message_txt'], messages_date=timezone.now())
                new_message.save()
        return HttpResponseRedirect(reverse('wall:home', ))

world/wall/templates/wall/index.html
<title> The Wolrd Wall</title>
<h2>The one & only one for everyone </h2>

{% if user.is_authenticated %}
  Hi <a href="{% url 'wall:profile' user.id %}">  {{ user.username }}!
  <p><a href="{% url 'wall:logout' %}">logout</a></p>
  <h3> Status </h3>
  <form action="{% url 'wall:publish' %}" method="post">
  {% csrf_token %}
      <label for="message_txt">What do you have in mind ?  </label><br />
      <input type="text" name="message_txt" id="messages_txt" value="" />
      <input type="submit" value="Publish" />
  </form>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'wall:signup' %}" > Signup</a> / <a href="{% url 'wall:login' %}">Signin</a>
{% endif %}

<h3> Publications</h3>
{% if comments %}
    <ul>
      {% for message in comments %}
        <li>
            "{{ message.messages_text}}". {{ message.messages_date}} ~ <a href="{% url 'wall:profile' message.user_id.id %}"> {{message.user_id}}  </a>
        </li>
      {% endfor %}
    </ul>
{% else %}
    <p>No texts are available.</p>
{% endif %}

world/wall/templates/wall/profile.html
<title> The Wolrd Wall</title>
<h2>You Have Reached {{ user.get_full_name }}</h2>


Contact via <a href="mailto:{{user.email}} " >{{user.get_full_name}}'s Mail</a>

{% if comments %}
<h3>{{ user.get_full_name }} Said the Following </h3>
    <ul>
      {% for message in comments %}
        <li>
            "{{ message.messages_text}}" . {{ message.messages_date}}  </a>
        </li>
      {% endfor %}
    </ul>
{% else %}
    <p>No texts are available.</p>
{% endif %}

world/wall/templates/wall/signup.html
<title>Sign Up</title>

  <h2>Sign up</h2>
  <form method="post">
   {% csrf_token %}
   {% for field in form %}
     <p>
       {{ field.label_tag }}<br>
       {{ field }}
       {% if field.help_text %}
         <small style="color: grey">{{ field.help_text }}</small>
       {% endif %}
       {% for error in field.errors %}
         <p style="color: red">{{ error }}</p>
       {% endfor %}
     </p>
   {% endfor %}
   <button type="submit">Sign up</button>
 </form>